name: Build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - "**.go"
      - go.sum
      - go.mod
  pull_request:
    paths:
      - .github/workflows/build.yml
      - "**.go"
      - go.sum
      - go.mod
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.14-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.14-
      - name: Build
        run: go build -v .
