name: Clean
on: push
jobs:
  codecov:
    name: Codecov branches
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init artifact
        run: mkdir -p artifact
      - name: branch in GitHub
        shell: bash
        run: |
          git fetch -p && git branch -r \
            | cut -d/ -f2- | cut -d' ' -f1 \
            | egrep -v '^HEAD$' \
            | tee artifact/github-branches.list
      - name: branch in Codecov
        shell: bash
        run: |
          curl "$codecov_url" --header "Authorization: token $token" \
            | jq -r '.branches[].branch' \
            | tee artifact/codecov-branches.list
        env:
          codecov_url: "https://codecov.io/api/gh/${{ github.repository }}/branches"
          token: ${{ secrets.CODECOV_API_TOKEN }}
      - name: detect target
        shell: bash
        run: |
          exists=$(cat artifact/github-branches.list)
          pattern="^($(echo $exists | tr ' ' '|'))$"
          egrep -q -v "$pattern" artifact/codecov-branches.list || exit 0
          egrep -h -v "$pattern" artifact/codecov-branches.list \
            | tee artifact/target.list
      - name: delete branches
        shell: bash
        run: |
          if [ ! -s artifact/target.list ] ; then
            exit 0
          fi
          cat artifact/target.list | while read branch ; do
            curl -X DELETE "$codecov_url/$branch" --header "Authorization: token $token"
            echo "$branch"
          done | tee artifact/deleted.list
        env:
          codecov_url: "https://codecov.io/api/gh/${{ github.repository }}/branch"
          token: ${{ secrets.CODECOV_API_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: artifact
