name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        gover:
          - "1.12"
          - "1.13"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    steps:
      - name: Set up Go ${{ matrix.gover }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.gover }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.gover }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.gover }}-

      - name: Download
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
