name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        gover:
          - "1.12"
          - "1.13"
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15
      fail-fast: false
    steps:
      - name: Set up Go ${{ matrix.gover }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.gover }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.gover }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.gover }}-

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
