name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gover:
          - "1.12"
          - "1.13"
      fail-fast: false
    steps:
      - name: Set up Go ${{ matrix.gover }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.gover }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
