name: MacOS
on: [push]
jobs:
  test:
    name: Test
    runs-on: macos-10.15
    timeout-minutes: 5
    strategy:
      matrix:
        go-version:
          - "1.12"
          - "1.13"
          - "1.14"
      fail-fast: false
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Test
        run: go test ./... -race

  # テストを待ってから処理しないと並列数に引っかかるのか処理が詰まることがある
  build:
    name: Build
    runs-on: macos-10.15
    timeout-minutes: 5
    needs: test
    strategy:
      matrix:
        go-version:
          - "1.14"
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Build
        run: go build -v .
