name: ReportCard
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/reportCard.yml
      - "**.go"
      - go.sum
      - go.mod
  workflow_dispatch:
    branches: ["master"]
jobs:
  report:
    name: Report Card
    runs-on: ubuntu-18.04
    timeout-minutes: 2
    steps:
      - name: Report
        uses: creekorful/goreportcard-action@v1.0
